.TH RETCHMAILRC 5 "July 2007" "Retchmail"
.SH NAME
retchmail.conf \- RetchMail configuration file
.SH DESCRIPTION
When
.B retchmail
starts, it first loads its configuration from
.hy 0
.IR $HOME/.retchmail/retchmail.conf ,
.hy 14
which contains basic information about all of the various accounts and
servers that you want to download your mail from, and deliver your mail to.
.sp
The configuration file
.hy 0
.I $HOME/.retchmail/retchmail.conf
.hy 14
is in Windows "ini" file format, with
.B sections
named in square brackets and a number of
.B variable = value
pairs within each section.
.sp
Here is a sample configuration file:
.PP
[POP Servers]
.br
testuser@example.com = password
.br
[POP Targets]
.br
testuser@example.com = localuser
.PP
The sample configuration file above contains all of the options
necessary to run retchmail to automatically deliver mail from
.hy 0
.B testuser@example.com
.hy 14
to
.hy 0
.B localuser.
.hy 14
when retchmail is invoked.
.PP
If you want retchmail to use SSL to encrypt all of the traffic between it
and your POP server, then it's as easy as adding :995 to the POP Servers
account name as follows:
.PP
[POP Servers]
.br
testuser@example.com:995 = password
.br
[POP Targets]
.br
testuser@example.com:995 = localuser
.PP 
If you wish to have retchmail use a mail delivery agent (MDA) other then
sendmail to deliver your mail you may also add a MDA Override option to your
config file as follows:
.PP
[POP Servers]
.br
testuser@example.com = password
.br
[MDA Override]
.br
testuser@example.com = qmail
.PP
.SH SEE ALSO
.BR retchmail (1)
.PP
.SH AUTHORS
Retchmail was originally written by Avery Pennarun and Patrick Patterson. Many people
have later contributed to it.
